### ISSUE TITLE
OpenShift

### ISSUE THREAD

**Issue by darkedges** [ForgeRock/forgeops#200]
Morning,
I have started to convert to OpenShift and have created https://bitbucket.org/account/user/darkedges/projects/OP to manage this.

Just wondering how I could best integrate with this project?

Regards
Nicholas Irving

**Comment by wstrange** [comment]
Hi Nicholas
The helm charts from this project should work with OpenShift. If you run into issues let us know and we can entertain making required changes. 

You will have to build the docker images in the docker/  folder, or you can optionally pull them as-is https://bintray.com/forgerock/public

**Comment by wstrange** [comment]
I am going to close this for now.   Please feel free to open up any specific issues that you encounter.

**Comment by darkedges** [comment]
Not a problem, there were the Source 2 Images versions so that you could use them instead of the docker images. Will try and figure out some other ways to keep them in alignment.
