### ISSUE TITLE
forgeops/docker/downloader/download root url incorrect?

### ISSUE THREAD

**Issue by c-mccutcheon** [ForgeRock/forgeops#471]
shell script forgeops/docker/downloader/download contains a root url to pull maven builds from of:

````https://maven.forgerock.org/repo/internal-releases/org/forgerock/````

With my artifactory key, this script fails to download the binaries locally and in a build environment (401 or 403), scanning the repository it appears the binaries are located under the following path:

````https://maven.forgerock.org/repo/private-releases/org/forgerock/````

Amending this in the downloader.sh successfully allowed us to build the 6.5.0 products, not sure if this is a bug or not, if so will raise a PR to fix?

**Comment by wstrange** [comment]
I think we need to make this configurable for internal / external users. I'll take a look at it - thanks for the bug report!
