### ISSUE TITLE
cts post load hook shell script not exists

### ISSUE THREAD

**Issue by c-mccutcheon** [ForgeRock/forgeops#472]
https://github.com/ForgeRock/forgeops/commit/b13079d313ff580a2caaa5bb111f23f0b2f23319

In reference to the above commit - using a 6.5.0 installation including using the core token store container as per the devOps guide, expects a shell script to be present and fails on container startup.

Should this shell script be present within the 6.5.0 OpenDJ container?

**Comment by c-mccutcheon** [comment]
Found the issue I think - this file is included but was an out of date branch our end! :)

**Comment by wstrange** [comment]
Awesome.
