### ISSUE TITLE
Docker pull from forgerock-docker-public.bintray.io/forgerock/ failing with Error response from daemon: manifest invalid: 

### ISSUE THREAD

**Issue by deevyea** [ForgeRock/forgeops#623]
**Describe the bug**
Docker pull from forgerock-docker-public.bintray.io/forgerock/ failing with Error response from daemon: manifest invalid: 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'helm charts
2. Install any one of the helm chart, ex: helm install --set domain=.acme.com openam
3.While I run kubectl get pods,
-  Pods go on -->Failed to pull image: ErrImagePull
4. Looks like the Repo forgerock-docker-public.bintray.io/forgerock/ needs to be authenticated.

**Expected behaviour**

1. when I run curl -X GET -u<username>:<API_KEY> https://forgerock-docker-public.bintray.io/v2/auth 
Output:
{"https://forgerock-docker-public.bintray.io":{"auth":"XXXXXXXXXXXXXXXX","email":"XXXXX"}}

2. The docker login is successfull, however when I try to pull the image locally it throws the below error,

docker pull forgerock-docker-public.bintray.io/forgerock/ds:latest
Error response from daemon: manifest invalid: manifest invalid

**Additional context**
The helm chart deployments always worked till yesterday. I have been facing this issue from today. Any help here is much appreciated

**Comment by wstrange** [comment]
Hi. Can you please switch to release/6.5.1 branch - the registry and tags have been updated.

Thanks!

**Comment by malotian** [comment]
Am getting the same issue, I ddint get the solution, can you explain further @wstrange

**Comment by dgoldssfo** [comment]
You'll need to check out the release/6.5.2 branch of forgeops now. Once you've done that, please make sure you're following the instructions in 
https://backstage.forgerock.com/docs/platform/6.5/devops-guide/#devops-implementation-docker-downloader

Keep in mind you can also use our Docker images as documented in https://backstage.forgerock.com/docs/platform/6.5/devops-guide/#devops-implementation-docker-eval. Just not for production deployments.
