### ISSUE TITLE
Missing docker image for AM 6.5.2.1

### ISSUE THREAD

**Issue by brissenden** [ForgeRock/forgeops#627]
Can you build docker image for AM 6.5.2.1? I can only find 6.5.2 on your docker repository:
https://console.cloud.google.com/gcr/images/forgerock-io/GLOBAL/openam

Cheers!

**Comment by wstrange** [comment]
Should be there now!

**Comment by brissenden** [comment]
Thank you!

**Comment by wstrange** [comment]
I'll ask our RE team to create another build. In the interim - you might want to look at the master branch and the docker/6.5/am-base - which lets you bring your own war file.  This will be the direction moving forward.
