### ISSUE TITLE
missing $ in eks-create-s3-policy.sh

### ISSUE THREAD

**Issue by ssdowd** [ForgeRock/forgeops#628]
Line 28 of eks-create-s3-policy.sh appears to be missing a $ in referring to the S3_BUCKET_NAME:
```
            "arn:aws:s3:::{S3_BUCKET_NAME}",
```

should be
```
            "arn:aws:s3:::${S3_BUCKET_NAME}",
```

**Comment by dgoldssfo** [comment]
Thanks for letting us know. I've fixed this.
