### ISSUE TITLE
Dockerfile build warning illegal reflective access

### ISSUE THREAD

**Issue by zbuckholz** [ForgeRock/forgeops#629]
docker/ds/cts/Dockerfile

Just FYI

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v7.Java7$1 (file:/opt/opendj/lib/groovy.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.vmplugin.v7.Java7$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by wstrange** [comment]
Thanks Zack. This is a known warning, and will be resolved when all the commons libraries are updated to OpenJDK 11.
