### ISSUE TITLE
Incorrect ds version in release/6.5.2

### ISSUE THREAD

**Issue by an-sush** [ForgeRock/forgeops#631]
The version mentioned in this [file](https://github.com/ForgeRock/forgeops/blob/113701a8d7cbb376bbf85e704aa8ea411d81b816/docker/ds/Dockerfile#L4) is invalid and docker build fails

**Comment by wstrange** [comment]
This has been updated in release/6.5.2
We also recommend using the update dockerfiles in the `master` branch under docker/6.5
