### ISSUE TITLE
release/6.5.2 has bad DS version in forgeops/docker/ds/Dockerfile

### ISSUE THREAD

**Issue by sgiorama** [ForgeRock/forgeops#634]
The ds Dockerfile in the release/6.5.2 branch has the version set as:

ARG VERSION="6.5.1-RC3"

"6.5.1-RC3" is no longer available in the repository.
I've done some tests on my fork setting this to "6.5.1" or "6.5.2". Both seem to work but not sure which one is correct and has been tested. Would have submitted a PR if I knew.

**Comment by wstrange** [comment]
PR is in flight to update this - but we are now recommending that folks use the `master` branch.

We have ported all the 6.5 dockerfiles to docker/6.5 - and updated to use the new skaffold / kustomize workflow.

Check it out!!!
