### ISSUE TITLE
Missing docker image for AM 6.5.2.2

### ISSUE THREAD

**Issue by brissenden** [ForgeRock/forgeops#636]
Hi, similar as here https://github.com/ForgeRock/forgeops/issues/627. Can you build docker image for OpenAM 6.5.2.2?

Cheers!

**Comment by wstrange** [comment]
We have updated documentation on building your own base images available here:
https://backstage.forgerock.com/docs/forgeops/6.5/sr-guide/#chap-sr-customization-docker

**Comment by brissenden** [comment]
Thanks, will check it out.
