### ISSUE TITLE
Perfomance tunning

### ISSUE THREAD

**Issue by daparthi001** [ForgeRock/forgeops#640]
Ctsstore is sitting at 35 gb limit what ever is allocated for the pod .
Can we introduce the -XX:ParallelGCThreads=n and also -XX:NewSize and -XX:MaxNewSize and -XX:+UseCGroupMemoryLimitForHeap?
Here is the running jvm config we have .
/usr/local/openjdk-8/jre/bin/java -server -Xmn512M -Xms3g -Xmx3g -XX:MaxTenuringThreshold=1 -XX:+UseCompressedOops -XX:+UseConcMarkSweepGC -XX:+PrintGC -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=5 -XX:GCLogFileSize=1024k -Xloggc:/opt/opendj/logs/gc.log -Dorg.opends.server.scriptName=start-ds org.opends.server.core.DirectoryServer --configFile /opt/opendj/config/config.ldif –nodetach

**Comment by wstrange** [comment]
Thanks for the suggestions. We are actively looking JVM options now- and there is alignment on what you are proposing. For example -XX:MaxTenuringThreshold=1
We will moving to container cgroups support (MaxRAMPercentage, etc.).
You won't see these setting directly in this repo as they will be defaulted in the upstream docker images.
