### ISSUE TITLE
HashiCorP & Google KMS vault support for Forgerock AM and DS. 

### ISSUE THREAD

**Issue by shubendhum** [ForgeRock/forgeops#641]
Hi Team,

Need to know, when will the Forgerock product natively support Google KMS or Hashicorp Vault for secrets and keys. This can help in secure container deployments and native key management in leu of file based key and secret stores.

**Comment by wstrange** [comment]
Integration with Cloud Secrets management is on the roadmap for 7.0.  Please engage with your ForgeRock sales team - they can provide feedback to our product manager to prioritize platform support.
Thanks!!!
