### ISSUE TITLE
Transaction id

### ISSUE THREAD

**Issue by daparthi001** [ForgeRock/forgeops#642]
Team 
I want to get the transaction id from nginx ingress controller to opeanm ,openidm .Do you have any document on doing it ?

**Comment by wstrange** [comment]
If this is an nginx question - can you ask on nginx-ingress K8S slack channel.

If this something else -can you expand on the use case. What do you expect AM/IDM to do ?

**Comment by daparthi001** [comment]
I want to track end to end transaction of each user from openam ,openidm and ds stores ?Is there way we can do that ?I am getting the nginx part working where the transaction id is coming up but the applications are not picking and printing in the logs .


https://backstage.forgerock.com/knowledge/kb/article/a56738565

**Comment by wstrange** [comment]
Have you made the configuration changes outlined in that article? 

(We will look at enabling this as a default in 7.0)
