### ISSUE TITLE
dns names

### ISSUE THREAD

**Issue by daparthi001** [ForgeRock/forgeops#643]
Is this inetentional to -0 for FQDN_DS

https://github.com/ForgeRock/forgeops/blob/stable/docker/6.5/ds-base/env.sh
# The FQDN all the serversin the statefulset. This is useful for backup or other commands that need to run on the first server.
**### export  FQDN_DS0=${DJ_INSTANCE}-0.${DJ_INSTANCE}
export  FQDN_DS1=${DJ_INSTANCE}-0.${DJ_INSTANCE}
export  FQDN_DS2=${DJ_INSTANCE}-0.${DJ_INSTANCE}**

# These environment variables are used to template the config.ldif file on startup
export FQDN_RS0=${DJ_INSTANCE}-0.${DJ_INSTANCE}:8989
export FQDN_RS1=${DJ_INSTANCE}-1.${DJ_INSTANCE}:8989
export FQDN_RS2=${DJ_INSTANCE}-2.${DJ_INSTANCE}:8989
export SERVER_FQDN="$FQDN"
export CHANGELOG_DB_DIRECTORY="data/db/changelogDb"

**Comment by wstrange** [comment]
This is fixed in 7.x
