### ISSUE TITLE
issue while running Skaffold 

### ISSUE THREAD

**Issue by sumit0704** [ForgeRock/forgeops#644]
Getting an error while building docker image

Fetched 325 kB in 1s (347 kB/s)
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/o/openldap/ldap-utils_2.4.45+dfsg-1ubuntu1.4_amd64.deb  404  Not Found [IP: 91.189.88.152 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by sumit0704** [comment]
![issue](https://user-images.githubusercontent.com/22254005/81423172-b67bd480-9119-11ea-8a19-e63ba9548190.PNG)

**Comment by sumit0704** [comment]
fixed by adding apt-get update --fix-missing in amster docker file

**Comment by wstrange** [comment]
Thanks for the issue report.  Fixed in master with
https://stash.forgerock.org/projects/CLOUD/repos/forgeops/pull-requests/2495/overview
