### ISSUE TITLE
Unable to build the image using skaffold

### ISSUE THREAD

**Issue by sumit0704** [ForgeRock/forgeops#646]
Hello Team,

I am unable to build the image using skaffold command mentioned in the document.Please refer to screenshot attached

![image](https://user-images.githubusercontent.com/22254005/83336157-bc775800-a276-11ea-861d-79a6d2b940dc.png)

**Comment by wstrange** [comment]
Hi - there is not enough debug info provided in that screen shot for us to help you.
It looks like you are trying to push to the docker hub - which is usually because your minikube context is not correct.

You might try using --default-repo gcr.io/my-repo/
on the skaffold command line
