### ISSUE TITLE
failed to build: getting hash for artifact - Running Skaffold Pipepline

### ISSUE THREAD

**Issue by ddarling85** [ForgeRock/forgeops#647]
Getting an error when running the skaffold pipeline to deploy the ForgeRock platform.  Below is the output I am getting.  

automate@hv-ubuntu2:/srv/forgerock-cdk/forgeops-clone$ skaffold run -f skaffold-6.5.yaml -p small
Generating tags...
 - am -> pmsacontainerregistry01.azurecr.io/cdm/am:latest
 - amster -> pmsacontainerregistry01.azurecr.io/cdm/amster:latest
 - idm -> pmsacontainerregistry01.azurecr.io/cdm/idm:latest
 - ds-cts -> pmsacontainerregistry01.azurecr.io/cdm/ds-cts:latest
 - ds-idrepo -> pmsacontainerregistry01.azurecr.io/cdm/ds-idrepo:latest
 - ig -> pmsacontainerregistry01.azurecr.io/cdm/ig:latest
 - forgeops-secrets -> pmsacontainerregistry01.azurecr.io/cdm/forgeops-secrets:latest
Checking cache...
 - am: Error checking cache.
failed to build: getting hash for artifact "am": getting dependencies for "am": parsing ONBUILD instructions: retrieving image "gcr.io/engineering-devops/am-base:6.5": GET https://gcr.io/v2/engineering-devops/am-base/manifests/6.5: MANIFEST_UNKNOWN: Failed to fetch "6.5" from request "/v2/engineering-devops/am-base/manifests/6.5".

**Comment by wstrange** [comment]
Derek - it looks like you are using an older version, Can you pull the latest tag (or master).

The courtesy base images are on `forgerock-io`, not `engineering-devops`. 

Note - you can build the base images yourself (mandatory for production) by downloading the am war file to docker/6.5/am-base. 

The `base` profile in skaffold-6.5 will build the base images

**Comment by ddarling85** [comment]
Thanks for the reply.  I'll do that and let you know.

**Comment by ddarling85** [comment]
Updating the repo did help tremendously.  Thanks.  However, I did have to checkout a newer tag to get all of the components to work properly.  It might be good to have the Cloud Deployment Model Cookbook for AKS document to be updated.  Thanks again!
