### ISSUE TITLE
Pulumi for EKS failing with extIngresstg80arn and extIngresstg443arn does not exist

### ISSUE THREAD

**Issue by jralmaraz** [ForgeRock/forgeops#650]
After successfully running the AWS infra pulumi stack, the eks stack is failing with 2 missing outputs from the infra stack:

    Error: Required output 'extIngresstg443arn' does not exist on stack 'aws-infra'.
and
    Error: Required output 'extIngresstg80arn' does not exist on stack 'aws-infra'.

Those are not mentioned as outputs though, so, I am wondering if I should create them manually or what else should it be done to overcome these expected parameters for Ingress:

Outputs:
    bastionEnable             : false
    bastionPublicIp           : "undefined"
    bastionSgId               : "undefined"
    clusterAdministratorRoleID: "clusterAdministratorRole-d9858ca"
    vpc                       : {
        id : "vpc-0186e1b6db722b778"
        urn: "urn:pulumi:aws-infra::aws-infra::awsx:x:ec2:Vpc::eks-cdm"
        vpc: {
            arn                         : "arn:aws:ec2:ap-southeast-2:******:vpc/vpc-0186e1b6db722b778"
            assignGeneratedIpv6CidrBlock: false
            cidrBlock                   : "192.168.0.0/16"
            defaultNetworkAclId         : "acl-03d24ca5313d40ab7"
            defaultRouteTableId         : "rtb-03bae1150aef9e9e0"
            defaultSecurityGroupId      : "sg-0ad3be7ea6331af96"
            dhcpOptionsId               : "dopt-6449ae01"
            enableClassiclink           : false
            enableClassiclinkDnsSupport : false
            enableDnsHostnames          : true
            enableDnsSupport            : true
            id                          : "vpc-0186e1b6db722b778"
            instanceTenancy             : "default"
            mainRouteTableId            : "rtb-03bae1150aef9e9e0"
            ownerId                     : "******"
            tags                        : {
                CreatedBy: "process.env.USER"
                Name     : "eks-cdm"
            }
            urn                         : "urn:pulumi:aws-infra::aws-infra::awsx:x:ec2:Vpc$aws:ec2/vpc:Vpc::eks-cdm"
        }
    }
    vpcCIDR                   : "192.168.0.0/16"
    vpcIsolatedSubnetsIds     : [
        [0]: "subnet-0631f6ac56f9e27e2"
        [1]: "subnet-0deeaa49e2601d4df"
        [2]: "subnet-03949218cdc5f69ac"
    ]
    vpcPrivateSubnetsIds      : [
        [0]: "subnet-0c4f58139b6c8c745"
        [1]: "subnet-09ca8cd7c3a89b87e"
        [2]: "subnet-0237899b3c6d31d4f"
    ]
    vpcPublicSubnetsIds       : [
        [0]: "subnet-0c7eafc521f68c8b2"
        [1]: "subnet-0fc05d7d9a0b24992"
        [2]: "subnet-05da433c7c8066feb"
    ]
    vpcid                     : "vpc-0186e1b6db722b778"

Resources:
    + 57 created

Duration: 2m9s

Permalink: file:///~/.pulumi/stacks/aws-infra.json

Thanks.

Jose

**Comment by jralmaraz** [comment]
Found HighAvailability config and piece of code that tells the assumption of loadbalancer service type will be used. Maybe document that default behaviour in the pulumi repo will help ? 

index.ts:if (highAvailability) //If highAvailability is False, it is assumed that the user will use type loadbalancer.

pulumi config set aws-infra:highAvailability true

Thanks.

Jose

**Comment by lee-baines** [comment]
Hi,  those 2 values are exported in the code and which results in them being available in the EKS stacks.  
```
export let extIngresstg80arn : any = undefined
export let extIngresstg443arn : any = undefined
```
What changes did you make to the eks stack?

**Comment by jralmaraz** [comment]
Hi,

I've pulled the code again and ran a pulumi refresh to make sure that extIngresstg80arn and extIngresstg443arn were being created. Then ran pulumi update and noted that the load-balancer was created.

Thanks.

Jose

**Comment by lee-baines** [comment]
Ok great. Glad its sorted
