### ISSUE TITLE
How to bind the External DS to IDM

### ISSUE THREAD

**Issue by RameshRM** [ForgeRock/forgeops#654]
Help me understand how to configure external DS with IDM, i am running a cloud setup

**Comment by wstrange** [comment]
I'm not sure if you are asking about DS as a repository (7.0 only), or as a managed target for sync?

In both cases, IDM must resolve the DNS name of the external directory server from your IDM pod.  This is going to depend on your deployment, and your cloud environment. This is not specific to the forgeops project, its more of a Kubernetes configuration issue.
