### ISSUE TITLE
helm deployment fails in version 7.5 due to attempting to execute a missing file /opt/opendj/default-scripts/init-and-restore.sh in the DS statefulsets

### ISSUE THREAD

**Issue by embesozzi** [ForgeRock/forgeops#685]
If you follow the oficial documentation, for version 7.5:
- https://backstage.forgerock.com/docs/forgeops/7.5/setup/minikube.html

It states:
```
$ cd forgeops
$ git checkout release/7.5-20240618
```
However, that branch does not include the following refactor:
[Refactoring ds init command to support runtime-scripts and default-scripts](https://github.com/ForgeRock/forgeops/compare/637a004bce07401116b81b5606cf541991220b73...7818bf9a7c52d27706e35aee206286d11033e12f)

As a result, the StatefulSets for the CTS and ID Repo attempt to run the command:
```yaml
command: ["/opt/opendj/runtime-scripts/init-and-restore.sh"]`
```
But the correct command should be:
```yaml
 command:
          - sh
          - -c
          - "/opt/opendj/runtime-scripts/init-and-restore.sh || /opt/opendj/default-scripts/init-and-restore.sh"
```

It seems that you tagged the DS images with the updated scripts but did not update the chart (oci://us-docker.pkg.dev/forgeops-public/charts/identity-platform) for version 7.5. This leads to the following error when running:

```bash
helm upgrade --install identity-platform \
 oci://us-docker.pkg.dev/forgeops-public/charts/identity-platform \
 --version 7.5 --namespace my-namespace \
 --set 'ds_idrepo.volumeClaimSpec.storageClassName=standard' \
 --set 'ds_cts.volumeClaimSpec.storageClassName=standard' \
 --set 'platform.ingress.hosts={forgeops.example.com}'
```
Error:
`
Message:      failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/opt/opendj/default-scripts/init-and-restore.sh": stat /opt/opendj/default-scripts/init-and-restore.sh: no such file or directory: unknown
`

**Comment by embesozzi** [comment]
Great, thanks for the quick response. I'll wait for your confirmation before proceeding with the deployment.

Which option do you think would be better: using the 7.5.0 image or 7.5.x with the new runtime scripts?

**Comment by lee-baines** [comment]
Either, I've pushed an updated version of the Helm Chart with the fix. So that will work. The image has also been restored too so either way, you should have any issue.  If you don't pull the updated Helm Chart, then you'll need make sure you're imagePullPolicy is set to Always so you get the updated image.  Let me know how you get on

**Comment by embesozzi** [comment]
Hi @lee-baines, the helm deployment worked well with restored image. 
Thanks you for the assistance.

**Comment by lee-baines** [comment]
Ok great.  I'll close the issue now
